[tool.poetry]
package-mode = false
name = "squebler-youtube-gui"

[tool.poetry.dependencies]
python = "^3.12"
google-api-python-client = "^2.120.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
